### PR TITLE
DM-20782: Flake8 cleanups

### PR DESCRIPTION
**Pull request by timj**
There are some oddities visible now that most of the flake8 warnings are gone:

```
./python/lsst/meas/extensions/ngmix/bootstrap.py:11:1: F401 'ngmix.gexceptions.GMixRangeError' imported but unused
./python/lsst/meas/extensions/ngmix/bootstrap.py:11:1: F401 'ngmix.gexceptions.BootPSFFailure' imported but unused
./python/lsst/meas/extensions/ngmix/bootstrap.py:11:1: F401 'ngmix.gexceptions.BootGalFailure' imported but unused
./python/lsst/meas/extensions/ngmix/bootstrap.py:418:13: F821 undefined name 'res'
./python/lsst/meas/extensions/ngmix/bootstrap.py:419:20: F821 undefined name 'res'
./python/lsst/meas/extensions/ngmix/mbobs_extractor.py:368:5: F841 local variable 'bits' is assigned to but never used
./python/lsst/meas/extensions/ngmix/priors.py:2:1: F401 'ngmix.joint_prior.PriorSimpleSep' imported but unused
./python/lsst/meas/extensions/ngmix/priors.py:2:1: F401 'ngmix.joint_prior.PriorBDFSep' imported but unused
./python/lsst/meas/extensions/ngmix/processCoaddsNGMix.py:776:13: F841 local variable 'model' is assigned to but never used
./python/lsst/meas/extensions/ngmix/processCoaddsNGMix.py:1095:9: F841 local variable 'front' is assigned to but never used
./python/lsst/meas/extensions/ngmix/processCoaddsNGMix.py:1166:13: F841 local variable 'model' is assigned to but never used
./tests/test_ngmix.py:149:9: F841 local variable 'npars' is assigned to but never used
```

I can  fix most of these by deleting them but the `res` variable one is vexing.

### CODE REVIEW

**Comment by esheldon** [comment]
the `res` variable problem is a code path that we are not using currently, which is why it hasn't caused a crash.

I'll make an issue and fix that separately.

**Comment by esheldon** [comment]
feel free to remove the unused imports and unused variables

**Comment by timj** [comment]
@esheldon I think I'm done. Can you please review?

**Review by esheldon — APPROVED** [review]
all changes look benign

**Comment by esheldon** [comment]
should we run the tests in travis?

**Comment by timj** [comment]
We can't easily run the tests in travis without a docker container or some kind of conda distribution. I did just try to run the tests on my laptop but they fail on this branch and on master because of some ngmix import problem so I don't know what to do (but it doesn't seem to be down to this branch).

**Comment by timj** [comment]
Ok. Master fails completely because it can't import PriorBDFSep.

My branch fixes that problem because I delete that unused import. I then get two test failures that are not caused by this branch. One is use of an `rng` parameter for a class that should not be there, the other is an image comparison.

**Comment by esheldon** [comment]
`PriorBDFSep` fail seems you have an old ngmix.

**Comment by esheldon** [comment]
`conda install ngmix`

**Comment by timj** [comment]
I'm using the ngmix from eups. I've only just realized that eups ngmix is no longer a formal dependency of meas_extensions_ngmix.

**Comment by timj** [comment]
Tests now pass so I'll merge once the travis checks complete.

**Pull request merged**
